# Generated by Django 3.2.16 on 2023-06-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_name',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='recipes_ingredients',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shopping_user_recipe',
        ),
    ]
