# Generated by Django 3.2.16 on 2023-06-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230605_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('pk',), 'verbose_name': 'Добавление рецепта в список покупок'},
        ),
    ]
