# Generated by Django 3.2.16 on 2023-06-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230608_0028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_name',
        ),
    ]
